/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as ConfirmacionComandaRouteImport } from './routes/confirmacion.$comanda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionComandaRoute = ConfirmacionComandaRouteImport.update({
  id: '/confirmacion/$comanda',
  path: '/confirmacion/$comanda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRoute
  '/progreso': typeof ProgresoRoute
  '/superadmin': typeof SuperadminRoute
  '/confirmacion/$comanda': typeof ConfirmacionComandaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRoute
  '/progreso': typeof ProgresoRoute
  '/superadmin': typeof SuperadminRoute
  '/confirmacion/$comanda': typeof ConfirmacionComandaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRoute
  '/progreso': typeof ProgresoRoute
  '/superadmin': typeof SuperadminRoute
  '/confirmacion/$comanda': typeof ConfirmacionComandaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/menu'
    | '/pedido'
    | '/progreso'
    | '/superadmin'
    | '/confirmacion/$comanda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/menu'
    | '/pedido'
    | '/progreso'
    | '/superadmin'
    | '/confirmacion/$comanda'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/menu'
    | '/pedido'
    | '/progreso'
    | '/superadmin'
    | '/confirmacion/$comanda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MenuRoute: typeof MenuRoute
  PedidoRoute: typeof PedidoRoute
  ProgresoRoute: typeof ProgresoRoute
  SuperadminRoute: typeof SuperadminRoute
  ConfirmacionComandaRoute: typeof ConfirmacionComandaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion/$comanda': {
      id: '/confirmacion/$comanda'
      path: '/confirmacion/$comanda'
      fullPath: '/confirmacion/$comanda'
      preLoaderRoute: typeof ConfirmacionComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MenuRoute: MenuRoute,
  PedidoRoute: PedidoRoute,
  ProgresoRoute: ProgresoRoute,
  SuperadminRoute: SuperadminRoute,
  ConfirmacionComandaRoute: ConfirmacionComandaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
