/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ConfirmacionComandaRouteImport } from './routes/confirmacion.$comanda'
import { Route as PedidoNumero_comandaRouteImport } from './routes/pedido.$numero_comanda'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ConfirmacionComandaRoute = ConfirmacionComandaRouteImport.update({
  id: '/confirmacion/$comanda',
  path: '/confirmacion/$comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoNumero_comandaRoute = PedidoNumero_comandaRouteImport.update({
  id: '/$numero_comanda',
  path: '/$numero_comanda',
  getParentRoute: () => PedidoRoute,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperadminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRouteWithChildren
  '/progreso': typeof ProgresoRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/confirmacion/$comanda': typeof ConfirmacionComandaRoute
  '/pedido/$numero_comanda': typeof PedidoNumero_comandaRoute
  '/superadmin/login': typeof SuperadminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRouteWithChildren
  '/progreso': typeof ProgresoRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/confirmacion/$comanda': typeof ConfirmacionComandaRoute
  '/pedido/$numero_comanda': typeof PedidoNumero_comandaRoute
  '/superadmin/login': typeof SuperadminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/menu': typeof MenuRoute
  '/pedido': typeof PedidoRouteWithChildren
  '/progreso': typeof ProgresoRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/confirmacion/$comanda': typeof ConfirmacionComandaRoute
  '/pedido/$numero_comanda': typeof PedidoNumero_comandaRoute
  '/superadmin/login': typeof SuperadminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/menu'
    | '/pedido'
    | '/progreso'
    | '/superadmin'
    | '/admin/login'
    | '/confirmacion/$comanda'
    | '/pedido/$numero_comanda'
    | '/superadmin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/menu'
    | '/pedido'
    | '/progreso'
    | '/superadmin'
    | '/admin/login'
    | '/confirmacion/$comanda'
    | '/pedido/$numero_comanda'
    | '/superadmin/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/menu'
    | '/pedido'
    | '/progreso'
    | '/superadmin'
    | '/admin/login'
    | '/confirmacion/$comanda'
    | '/pedido/$numero_comanda'
    | '/superadmin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MenuRoute: typeof MenuRoute
  PedidoRoute: typeof PedidoRouteWithChildren
  ProgresoRoute: typeof ProgresoRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  ConfirmacionComandaRoute: typeof ConfirmacionComandaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/confirmacion/$comanda': {
      id: '/confirmacion/$comanda'
      path: '/confirmacion/$comanda'
      fullPath: '/confirmacion/$comanda'
      preLoaderRoute: typeof ConfirmacionComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$numero_comanda': {
      id: '/pedido/$numero_comanda'
      path: '/$numero_comanda'
      fullPath: '/pedido/$numero_comanda'
      preLoaderRoute: typeof PedidoNumero_comandaRouteImport
      parentRoute: typeof PedidoRoute
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof SuperadminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PedidoRouteChildren {
  PedidoNumero_comandaRoute: typeof PedidoNumero_comandaRoute
}

const PedidoRouteChildren: PedidoRouteChildren = {
  PedidoNumero_comandaRoute: PedidoNumero_comandaRoute,
}

const PedidoRouteWithChildren =
  PedidoRoute._addFileChildren(PedidoRouteChildren)

interface SuperadminRouteChildren {
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminLoginRoute: SuperadminLoginRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MenuRoute: MenuRoute,
  PedidoRoute: PedidoRouteWithChildren,
  ProgresoRoute: ProgresoRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  ConfirmacionComandaRoute: ConfirmacionComandaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
